[project]
site_name = "ezp"
site_url = "https://tlcfem.github.io/ezp/"
site_author = "Theodore Chang"
copyright = "Copyright © 2025-2026 Theodore Chang"

extra_javascript = [
"javascripts/mathjax.js",
"https://polyfill.io/v3/polyfill.min.js?features=es6",
"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
]

nav = [
  {"Home" = "README.md"},
  {"Introduction" = [
    "Intro/Motivation.md",
    "Intro/Compilation.md",
  ]},
  {"Guide" = [
    "Guide/Usage.md",
    "Guide/Custom.md",
    "Guide/MPI.md",
    "Guide/Standalone.md",
  ]},
  {"Solvers" = [
    {"Dense" = [
      "Solvers/Dense/pdbsv.md",
      "Solvers/Dense/pgbsv.md",
      "Solvers/Dense/pgesv.md",
      "Solvers/Dense/pgesvx.md",
      "Solvers/Dense/ppbsv.md",
      "Solvers/Dense/pposv.md",
      "Solvers/Dense/pposvx.md",
    ]},
    {"Sparse" = [
      "Solvers/Sparse/lis.md",
      "Solvers/Sparse/mumps.md",
      "Solvers/Sparse/pardiso.md",
    ]},
  ]},
  {"Doxygen" = "doxygen/html/index.html"}
]

[project.theme]
features = [
"navigation.instant",
"navigation.instant.progress",
"navigation.tabs",
"navigation.tabs.sticky",
"navigation.tracking",
"navigation.sections",
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
linenums = true
[project.markdown_extensions.pymdownx.blocks.caption]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tilde]
