var annotated_dup =
[
    [ "ezp", null, [
      [ "detail", null, [
        [ "abstract_solver", "d0/df0/classezp_1_1detail_1_1abstract__solver.html", null ],
        [ "band_solver", "d0/db0/classezp_1_1detail_1_1band__solver.html", null ],
        [ "csr_comparator", "db/d43/classezp_1_1detail_1_1csr__comparator.html", null ],
        [ "full_solver", "df/df0/classezp_1_1detail_1_1full__solver.html", "df/df0/classezp_1_1detail_1_1full__solver" ],
        [ "lis_env", "de/dca/structezp_1_1detail_1_1lis__env.html", null ],
        [ "lis_matrix", "d1/d8e/classezp_1_1detail_1_1lis__matrix.html", null ],
        [ "lis_solver", "d6/dd6/classezp_1_1detail_1_1lis__solver.html", null ],
        [ "lis_vector", "d3/dae/classezp_1_1detail_1_1lis__vector.html", null ],
        [ "mumps_struc", "df/d7f/structezp_1_1detail_1_1mumps__struc.html", null ],
        [ "mumps_struc< complex16 >", "d4/d83/structezp_1_1detail_1_1mumps__struc_3_01complex16_01_4.html", null ],
        [ "mumps_struc< complex8 >", "d6/dae/structezp_1_1detail_1_1mumps__struc_3_01complex8_01_4.html", null ],
        [ "mumps_struc< double >", "df/d5e/structezp_1_1detail_1_1mumps__struc_3_01double_01_4.html", null ],
        [ "mumps_struc< float >", "db/d3e/structezp_1_1detail_1_1mumps__struc_3_01float_01_4.html", null ]
      ] ],
      [ "band_mat", "d9/d24/structezp_1_1band__mat.html", null ],
      [ "band_symm_mat", "d8/d3f/structezp_1_1band__symm__mat.html", null ],
      [ "base_mat", "d3/d46/structezp_1_1base__mat.html", null ],
      [ "blacs_base", "d6/d56/classezp_1_1blacs__base.html", null ],
      [ "blacs_context", "df/dc0/classezp_1_1blacs__context.html", "df/dc0/classezp_1_1blacs__context" ],
      [ "blacs_env", "da/d77/classezp_1_1blacs__env.html", null ],
      [ "full_mat", "d0/d58/structezp_1_1full__mat.html", null ],
      [ "lis", "d1/de4/classezp_1_1lis.html", null ],
      [ "mumps", "d6/dbe/classezp_1_1mumps.html", "d6/dbe/classezp_1_1mumps" ],
      [ "pdbsv", "de/d4c/classezp_1_1pdbsv.html", "de/d4c/classezp_1_1pdbsv" ],
      [ "pgbsv", "d1/d7e/classezp_1_1pgbsv.html", "d1/d7e/classezp_1_1pgbsv" ],
      [ "pgesv", "d5/d48/classezp_1_1pgesv.html", null ],
      [ "pgesvx", "d5/d6a/classezp_1_1pgesvx.html", null ],
      [ "ppbsv", "d3/df1/classezp_1_1ppbsv.html", "d3/df1/classezp_1_1ppbsv" ],
      [ "pposv", "de/d12/classezp_1_1pposv.html", null ],
      [ "pposvx", "d0/d05/classezp_1_1pposvx.html", null ],
      [ "sparse_coo_mat", "d4/d16/structezp_1_1sparse__coo__mat.html", null ],
      [ "sparse_csr_mat", "d6/d5b/structezp_1_1sparse__csr__mat.html", null ],
      [ "WorkType", "da/d62/structezp_1_1WorkType.html", null ],
      [ "WorkType< complex16 >", "d2/dac/structezp_1_1WorkType_3_01complex16_01_4.html", null ],
      [ "WorkType< complex8 >", "d1/d01/structezp_1_1WorkType_3_01complex8_01_4.html", null ],
      [ "WorkType< double >", "d0/d47/structezp_1_1WorkType_3_01double_01_4.html", null ],
      [ "WorkType< float >", "d6/d6b/structezp_1_1WorkType_3_01float_01_4.html", null ]
    ] ],
    [ "bandsymm_mat", "d0/d33/classbandsymm__mat.html", null ],
    [ "general_mat", "d8/d10/classgeneral__mat.html", null ],
    [ "lis", "d5/d19/classlis.html", null ],
    [ "LIS_COMMTABLE_STRUCT", "d1/d04/structLIS__COMMTABLE__STRUCT.html", null ],
    [ "LIS_MATRIX_CORE_STRUCT", "dc/d56/structLIS__MATRIX__CORE__STRUCT.html", null ],
    [ "LIS_MATRIX_DIAG_STRUCT", "dc/dff/structLIS__MATRIX__DIAG__STRUCT.html", null ],
    [ "LIS_MATRIX_ILU_STRUCT", "de/dbe/structLIS__MATRIX__ILU__STRUCT.html", null ],
    [ "LIS_MATRIX_STRUCT", "d0/d39/structLIS__MATRIX__STRUCT.html", null ],
    [ "LIS_PRECON_STRUCT", "de/db7/structLIS__PRECON__STRUCT.html", null ],
    [ "LIS_SOLVER_STRUCT", "d4/d5d/structLIS__SOLVER__STRUCT.html", null ],
    [ "LIS_VECTOR_STRUCT", "d0/d77/structLIS__VECTOR__STRUCT.html", null ],
    [ "mat", "d0/d36/classmat.html", null ],
    [ "mumps", "df/d0c/classmumps.html", null ],
    [ "mumps_parser", "d4/d64/classmumps__parser.html", null ],
    [ "pardiso", "dc/d7b/classpardiso.html", null ],
    [ "pdbsv", "d0/de4/classpdbsv.html", null ],
    [ "pgbsv", "d4/d10/classpgbsv.html", null ],
    [ "pgesv", "dc/d13/classpgesv.html", null ],
    [ "pgesvx", "df/d1a/classpgesvx.html", null ],
    [ "ppbsv", "d8/dba/classppbsv.html", null ],
    [ "pposv", "db/db1/classpposv.html", null ],
    [ "pposvx", "d4/d47/classpposvx.html", null ]
];