name: master
on:
  push:
jobs:
  linux-dev:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        mpi: [ impi, mpich, openmpi ]
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Compile
        run: |
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update && sudo apt-get install intel-oneapi-mkl-devel intel-oneapi-mpi-devel
          if [ "${{ matrix.mpi }}" == "impi" ]; then
            source /opt/intel/oneapi/setvars.sh
            export MPI_HOME=/opt/intel/oneapi/mpi/latest
          elif [ "${{ matrix.mpi }}" == "mpich" ]; then
            wget -q https://github.com/TLCFEM/prebuilds/releases/download/latest/MPICH-linux.tar.gz
            tar -xzf MPICH-linux.tar.gz
            sudo mv MPICH /MPICH
            export MPI_HOME=/MPICH
          elif [ "${{ matrix.mpi }}" == "openmpi" ]; then
            wget -q https://github.com/TLCFEM/prebuilds/releases/download/latest/OpenMPI-linux.tar.gz
            tar -xzf OpenMPI-linux.tar.gz
            sudo mv OpenMPI /OpenMPI
            export MPI_HOME=/OpenMPI
          fi
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DEZP_TEST=ON -DEZP_STANDALONE=ON -DMPI_HOME=$MPI_HOME -DEZP_ASAN=ON ..
          cmake --build . --target pardiso.memleak
          ./pardiso.memleak
